# Same as Black
line-length = 88
indent-width = 4

# Assume Python 3.10
target-version = "py310"

[lint]
select = ["E4", "E7", "E9", "F", "G", "B", "E", "W", "C90", "I", "UP", "PGH", "INT"]
ignore = ["UP031", "UP032", "B027"]

[lint.isort]
default-section = "third-party"
known-first-party = ["exchrate"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder"
]


[lint.mccabe]
max-complexity = 10

[lint.pyupgrade]
keep-runtime-typing = true

[format]
quote-style = "preserve"
